### ISSUE TITLE
2015년 1월 3일 2월 파이썬 세미나 준비모임

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/event#2]
@lexifdev @Bloodevil 참가합니다. 참여하실분은 코멘트로 달아주세요.
- 일시 : 1월 3일 토요일
- 장소 : 파이조그를 하는 어딘가.
- 할일 : 2015년 2월 파이썬 세미나를 튜토리얼로 진행하기 위한 준비. 아마도 기본적인 일시, 장소, 튜토리얼 컨셉등을 잡을 것 같지만 당일 한 일은 이쪽 이슈에 달고 모임이 끝나면 close합니다. 거기서 나온 부수적인 이슈는 같은 마일스톤으로 이슈생성하겠습니다.

**Comment by tebica** [comment]
당일 별일 없으면 참가하려고 합니다

**Comment by lqez** [comment]
한 시간이라도 시간을 내서 참석해보도록 하겠습니다.

**Comment by OuO** [comment]
별 다른 일정이 없으니 참석하도록 하겠습니다. 관심관심....

**Comment by Bloodevil** [comment]
https://github.com/pythonkr/pyconkr-2015/issues/21 회의록은 이쪽에서 보세요. 이슈 닫습니다.
