### ISSUE TITLE
파이썬 한국 사용자 모임 2월 세미나 토즈 예약

### ISSUE THREAD

**Issue by lqez** [pythonkr/event#4]

**Comment by Bloodevil** [comment]
1월 14일에 토즈타워 예약이 가능.
강남 토즈타워점으로 하면 됨. 20명 이상 방 3개. 
예약 후 D2 지원으로 하면 됨.

**Comment by darjeeling** [comment]
2월 14일 1시부터 6시
실제로 튜토리얼 시간은 3시간임

**Comment by darjeeling** [comment]
토즈타워점 1실 예약 완료
지 점 :   토즈타워점     모임일 : 2015-02-14
시 간 :   13:00 부터 (5시간이용)        인 원 :   20명 ( 30인분 준비 )
부 스 :   2층 단독홀(30~40인)

토즈타워점 2실 예약 완료
동일 시간 18인 부스 예약
