### ISSUE TITLE
ipython 통계 

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/event#7]
자료같은것 올려주시고,  발표끝나면 닫아주세요. :)

**Comment by Bloodevil** [comment]
9명 결제 11명 신청

@lexifdev 슬님도 어서 본인 소개와 교육 목차같은거 알려주세요 (코멘트로 달아주세용)

**Comment by lexifdev** [comment]
내용 한번 써 봤습니다. 좀 주절이 많은것 같긴 한데 리뷰 부탁드립니다.

```
4시간의 프로그램으로 데이터 분석가가 될 수는 없습니다.

수많은 분석 방법 중 한가지 주제만 가지고도 4시간은 족히 이야기 할 수 있으며,
프로그래밍에 대한 이야기 만으로도 4시간은 턱없이 부족한 시간입니다.

그럼에도 불구하고.. 
4시간 동안 할 수 있는 최선은 무엇일까 고민하여 다음과 같은 내용을 정하게 되었습니다.
* 많이 쓰이는 데이터 분석 방법들은 어떤것들이 있는지 개략적으로 알게 됩니다.
* 각 방법들에 대해서 가장 간단한 형태로 실제로 돌아가는 코드를 작성하게 됩니다.
* 가급적이면 단계별로 눈으로 보고 생각할 수 있는 다양한 그래프를 그려봅니다.

실제로는 다음 두가지가 훨씬 중요한 내용입니다만, 이번 프로그램에서는 다루지 않을 예정입니다.
* 깨끗한 데이터를 구하고 정제하는것
* 모델을 구현한 이후 평가하고 튜닝해 나가는것


현재까지 포함된 내용은 다음과 같은것이 있고 항목의 추가/삭제는 당일날 까지 가능합니다.
방법 : 값, 척도, 최소값, 최대값, 평균, 표준편차, t검증, 상관성분석, 회귀분석, kmeans, 나이브 베이지안 분류기
라이브러리 : numpy, scipy, pandas, bokeh, scikit, konlpy

몇가지 내용들은 중요함에도 불구하고 시간과 효과 사이에서 고민중에 있습니다.
후보 : 시계열 예제, 위치정보/지도 예제, SVM, kNN, MCMC
```

**Comment by iz4blue** [comment]
제 스타일로 조금 손을 본 내용입니다. 그냥 어투만 조금 바꾸어봤습니다.

강의 계획
4시간의 프로그램으로 데이터 분석을 논하는 것은 어려운 일입니다.
그럼에도 불구하고.. 4시간 동안 할 수 있는 최선은 무엇일까 고민하여 다음의 목표를 정해보았습니다.
- 많이 쓰이는 데이터 분석 방법들은 어떤것들이 있는지 개략적으로 경험해 봅니다.
- 각 방법들에 대해서 가장 간단한 형태로 실제로 돌아가는 코드를 작성하여 봅니다.
- 가급적이면 단계별로 눈으로 보고 생각할 수 있는 다양한 그래프를 그려 봅니다.

이 강의를 듣게 되시면 아래와 같은 영역의 방향을 잡을 수 있게 됩니다.
다만 이 부분은 개인의 탐구 영역으로 남겨 두겠습니다.
- 깨끗한 데이터를 구하고 정제하는것
- 모델을 구현한 이후 평가하고 튜닝해 나가는것

본 강의에서 특별히 다루었으면 하는 내용이 있으면 메일로 문의 주시기 바랍니다.
방법 : 값, 척도, 최소값, 최대값, 평균, 표준편차, t검증, 상관성분석, 회귀분석, kmeans, 나이브 베이지안 분류기
라이브러리 : numpy, scipy, pandas, bokeh, scikit, konlpy
실습후보 : 시계열 예제, 위치정보/지도 예제, SVM, kNN, MCMC

**Comment by iz4blue** [comment]
김슬님의 이번 발표 자료 내용입니다. https://github.com/lexifdev/statbystep
추가로 기록하실 것이 있으면 기록하시고 close 하시면 될 것 같습니다. @lexifdev
