### ISSUE TITLE
2015년 2월 세미나 티저 페이지

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/event#8]
@lqez 님이 하게 되었나요? 아니면 @iz4blue  인가요. 몰라서 일단 모두 호출 합니다. 정리부탁드립니다.

**Comment by lqez** [comment]
티저 페이지를 페이스북 포스트가 아니라 별도 페이지로 제작하는 거인가요? 저는 현재 PyCon Korea 2015 CFP + 티저를 준비하고 있습니다.

만약에 페이지가 필요하면 다시 할당해주세요.

**Comment by Bloodevil** [comment]
아 입금받는 페이지가 있다고 생각해서요. 없어도 된다면 상관 없습니다. @iz4blue 님의 의견 들어보고 닫도록 하겠습니다.

**Comment by iz4blue** [comment]
티져 이긴 한데 내용정도는 올려야 하지 않나 해서 기다리고 있습니다
티져 보다는 사전 등록을 위한 페이지 형태로 준비되고 있었습니다.

**Comment by Bloodevil** [comment]
사전등록페이지 http://goo.gl/dP6PoR 가 열려서 코멘트 씁니다. 
@iz4blue 이쪽에 소스 올려주실 수 있으면 (히스토리 관리용으로) 올려주세요. 아니면 제가 wget 해서 내용만 옮겨놓도록 하겠습니다. 소스 올리셨으면 close해주시면 됩니다. :)

**Comment by lqez** [comment]
fairbrite 는 @iz4blue 님이 개인적으로 운영하고 계신 사이트로 알고 있어서, 별도로 소스를 올릴 필요 까지는 없지 않나 싶습니다.

**Comment by Bloodevil** [comment]
보고싶은건 소스가 아니고 내용이긴 합니다. history용으로... ㅠ 근데 뭐 어떻게 되겠죠 일단 발표도 진행되고 있으니 close 합니다.
