### ISSUE TITLE
2015 첫 튜토리얼 종료 이후 만족도 설문 모집

### ISSUE THREAD

**Issue by iz4blue** [pythonkr/event#9]
약간 늦은 감이 있긴 하지만... (1~2일정도?) 튜토리얼 종료 설문을 돌려야 합니다.
질문 항목을 정하는 것이 좀 망설여져서 문의 드려 봅니다.
@lexifdev @perhapsspy 혹시 강의 내용과 관련된 추가 질문 사항이 있으면 남겨 주세요.

강의 준비에 관련된 설문
- 강의 장소는 적절하셨나요? ( 1~5 점 )
- 강의 장소에 관련된 조언 사항이 있으신가요? ( 주관식 )
- 신청 절차는 적절하였나요? ( 1~5 점 )
- 신청 절차를 개선해야 한다면 어떤 부분이 있을까요? ( 주관식 )
- 강의에 대한 사전 안내에 보충 되어야 하는 부분은 어떤 부분이 있을까요? ( 주관식 )

강의 진행에 관련된 설문
- 강의 내용과 진행은 적절하였나요? ( 1~5 점 )
- 강의 내용과 진행에 대해서 조언 사항이 있으신가요? ( 주관식 )
- 강의 난이도는 만족 스러우셨나요? ( 너무 쉬웠음 ~ 너무 어려웠음, 1~5 점 )
- 튜토리얼 진행시 튜터의 도움이 만족 스러우셨나요? ( 도움이 안됨, 도움을 받아 본적 없음, 잘 모르겠음, 도움이 됨, 매우 필요 )
- 튜터의 준비사항이나 기타 튜터가 도움을 주었으면 하는 부분은? ( 주관식 )
- 참가비가 적절하였다고 생각하시나요? ( 많이 비쌈 ~ 많이 저렴함, 1~5 점 )

추후 튜토리얼에 관련된 설문
- 추후 다음 레벨의 튜토리얼을 진행한다면 참석 하실 의향이 있으신가요? ( Yes, NO )
- python 에 관련된 다른 튜토리얼을 원하신다면 어떤 주제를 원하시나요? ( 주관식 )
- python 을 현업에서 사용중이면 어떤 분야에 대해서 사용중이신지요? ( 주관식 )

**Comment by lexifdev** [comment]
저는 적절해 보입니다.

**Comment by lexifdev** [comment]
신청시 강의에 대한 설명이 충분했는지
설명한 내용과 일치하는지 정도가 추가되면 좋겠습니다.

**Comment by iz4blue** [comment]
@lexifdev 김슬님 강의전에 질문하셨던 질문지 공유해주시면 감사하겠습니다.
다음에 행사를 준비할 때 신청전에 참고하면 좋을 것 같아요.
